/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/api`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/friends` | `/friends`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ChatList`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ChatRoom`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CreatePost`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Friends`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PostDetail`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/api`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/friends` | `/friends`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ChatList`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ChatRoom`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CreatePost`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Friends`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/PostDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/api${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chats${`?${string}` | `#${string}` | ''}` | `/chats${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/friends${`?${string}` | `#${string}` | ''}` | `/friends${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/screens/ChatList${`?${string}` | `#${string}` | ''}` | `/screens/ChatRoom${`?${string}` | `#${string}` | ''}` | `/screens/CreatePost${`?${string}` | `#${string}` | ''}` | `/screens/Friends${`?${string}` | `#${string}` | ''}` | `/screens/Home${`?${string}` | `#${string}` | ''}` | `/screens/Login${`?${string}` | `#${string}` | ''}` | `/screens/PostDetail${`?${string}` | `#${string}` | ''}` | `/screens/Profile${`?${string}` | `#${string}` | ''}` | `/screens/Register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/api`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/friends` | `/friends`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ChatList`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ChatRoom`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CreatePost`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Friends`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PostDetail`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
