# Generated by Django 5.2.6 on 2025-09-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_make_email_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Follow'), (3, 'Comment'), (4, 'Reply'), (5, 'Like-Comment'), (6, 'Like-Reply'), (7, 'Friend Request')]),
        ),
    ]
