# Generated by Django 5.2.6 on 2025-09-10 08:42

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210403_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='sender',
            new_name='from_profile',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='receiver',
            new_name='to_profile',
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('from_profile', 'to_profile')},
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
