# Generated by Django 5.2.6 on 2025-09-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_fix_otp_defaults'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX unique_email_idx ON auth_user (email);",
            reverse_sql="DROP INDEX IF EXISTS unique_email_idx;"
        ),
    ]
