# Generated by Django 5.2.6 on 2025-09-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complete_profile',
            field=models.BooleanField(default=False),
        ),
    ]
