# Generated by Django 5.2.6 on 2025-09-12 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_complete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_online_status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_online_status', models.BooleanField(default=True, help_text="Show when you're online to other users")),
                ('show_last_seen', models.BooleanField(default=True, help_text='Show when you were last seen')),
                ('allow_messages_from', models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends only'), ('none', 'No one')], default='everyone', help_text='Who can send you messages', max_length=20)),
                ('allow_friend_requests', models.BooleanField(default=True, help_text='Allow others to send you friend requests')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], default='public', help_text='Who can see your profile', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
